/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.pkg1;

import java.applet.AudioClip;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.PrintStream;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sun.audio.AudioPlayer;
import sun.audio.AudioStream;



/**
 *
 * @author ntrog
 */
public class Game_Applet extends javax.swing.JApplet {

    /**
     * Initializes the applet Game_Applet
     */
    @Override
    public void init() {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Game_Applet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Game_Applet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Game_Applet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Game_Applet.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        
        
        /* Create and display the applet */
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();

        jInternalFrame1.setVisible(true);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Player 1 Name");

        jLabel2.setText("Player 2 Name");

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jButton1.setText("Start Button");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Roll");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel1.setLayout(null);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG"))); // NOI18N
        jToggleButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton1);
        jToggleButton1.setBounds(90, 10, 90, 90);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG"))); // NOI18N
        jToggleButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton2);
        jToggleButton2.setBounds(230, 10, 90, 90);

        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG"))); // NOI18N
        jToggleButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton3);
        jToggleButton3.setBounds(370, 10, 90, 90);

        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG"))); // NOI18N
        jToggleButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton4);
        jToggleButton4.setBounds(90, 110, 90, 90);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG"))); // NOI18N
        jToggleButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton5);
        jToggleButton5.setBounds(230, 110, 90, 90);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG"))); // NOI18N
        jToggleButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jToggleButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jToggleButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jToggleButton6);
        jToggleButton6.setBounds(370, 110, 90, 90);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/wood 4.jpg"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(-2, -6, 650, 240);

        jPanel2.setLayout(new javax.swing.OverlayLayout(jPanel2));

        jButton3.setText("Stop Game");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Next");
        jButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("P1 Score");
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("P2 Score");
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
                .addGap(18, 28, Short.MAX_VALUE)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                .addComponent(jTextField2)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                            .addComponent(jButton1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3)
                            .addComponent(jButton4))
                        .addGap(18, 18, 18)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton5)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton6)
                            .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jInternalFrame1)
        );
    }// </editor-fold>//GEN-END:initComponents
//NAME INPUT 1
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        jTextField1.setToolTipText("Enter the name of player 1");
        String p1name = jTextField1.getText(); 
        game.p1.setName(p1name);
        this.repaint();
    }//GEN-LAST:event_jTextField1ActionPerformed
//NAME INPUT 2
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        jTextField2.setToolTipText("Enter the name of player 2");
        String p2name = jTextField2.getText();
        game.p2.setName(p2name);
        this.repaint();
    }//GEN-LAST:event_jTextField2ActionPerformed
//START GAME BUTTON
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jButton1.setToolTipText("This button will start the game. ONLY CLICK ONCE TO START!");
        Rules.startRules();
        initialize_new();
        //System.out.println(game.p1.getName());
        //System.out.println(game.p2.getName());
    }//GEN-LAST:event_jButton1ActionPerformed
//ROLL BUTTON
    
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        //Add the dice roll sound effect
        jButton2.setToolTipText("Click this button to roll");
        InputStream music;
        try{
            music = new FileInputStream(new File("C:\\Users\\ntrog\\OneDrive\\Documents\\NetBeansProjects\\Project 1\\src\\project\\pkg1\\Dice Roll Sound Effect.wav"));
            AudioStream rolling = new AudioStream(music);
            AudioPlayer.player.start(rolling);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getLocalizedMessage());
        }
        game.rollDice();
        changeDiceIcon();
        System.out.println("Select the dice you would like to keep?");
        if(game.d1.isKept && game.d2.isKept && game.d3.isKept && game.d4.isKept && game.d5.isKept && game.d6.isKept){
            System.out.println("Looks like you have selected all the dice, click the NEXT button to bank your score");
        }else{
            System.out.println("If you would like to roll again click the roll button or click the next button to bank your current score");
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed
//DICE 5
    private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton5ActionPerformed
        // TODO add your handling code here:
        jToggleButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d5.isKept()){
            game.d5.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton5ActionPerformed
//DICE 1
    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        jToggleButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d1.isKept()){
            game.d1.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton1ActionPerformed
//DICE 2
    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
        jToggleButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d2.isKept()){
            game.d2.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton2ActionPerformed
//DICE 3
    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
        // TODO add your handling code here:
        jToggleButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d3.isKept()){
            game.d3.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton3ActionPerformed
//DICE 4
    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        // TODO add your handling code here:
        jToggleButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d4.isKept()){
            game.d4.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton4ActionPerformed
//DICE 6
    private void jToggleButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton6ActionPerformed
        // TODO add your handling code here:
        jToggleButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 204, 0)));
        if(!game.d6.isKept()){
            game.d6.setisKept();
        }
        this.repaint();
    }//GEN-LAST:event_jToggleButton6ActionPerformed
//EXIT BUTTON
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton3.setToolTipText("This button will stop the game and close the window");
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed
//NEXT BUTTON
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        jButton4.setToolTipText("Push this button after you have finished rolling during your turn");
        bank.testforoccurencestot(game);
        bank.testfortrips(game);
        //bank.totalCombinations();
        next();
        bank.resetValues();
        testforWin();
    }//GEN-LAST:event_jButton4ActionPerformed
//p1 points box
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        jTextField3.setText(game.p1.getScore() + " points");
        this.repaint();
    }//GEN-LAST:event_jButton5ActionPerformed
//p2 points box
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        jTextField4.setText(game.p2.getScore() + " points");
        this.repaint();
    }//GEN-LAST:event_jButton6ActionPerformed


    Game game = new Game();
    Bank bank = new Bank(game);
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    // End of variables declaration//GEN-END:variables
    
    
    private Game_Applet(javax.swing.JTextArea jTextArea1){
        this.jTextArea1 = jTextArea1;
    }
    
    public void write(int b) throws IOException {
        jTextArea1.append(String.valueOf((char)b));
        jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
    }
   
    PrintStream customPrint = new PrintStream(new OutputStream() {
        @Override
        public void write(int b) throws IOException {
            jTextArea1.append(String.valueOf((char)b));
            // scrolls the text area to the end of data
            jTextArea1.setCaretPosition(jTextArea1.getDocument().getLength());
        }
    });
    
    
    public Game_Applet(){
        System.setOut(customPrint);
    }
    
    public void initialize_new(){
        game.p1.setName(jTextField1.getText());
        game.p2.setName(jTextField2.getText());
        System.out.println("Looks like we have two players: " + game.p1.getName() + " and " + game.p2.getName());
        System.out.println("In this case " + game.p1.getName() + " will go first");
        game.currentPlayer = game.p1;
        System.out.println("Click the roll button to begin your turn");
    }
    
    public void resetDice(){
        game.d1.isKept = false;
        game.d2.isKept = false;
        game.d3.isKept = false;
        game.d4.isKept = false;
        game.d5.isKept = false;
        game.d6.isKept = false;
    }
    
    public void resetBorder(){
        jToggleButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton4.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton5.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jToggleButton6.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
    }
    
    public void changeDiceIcon(){
        if(!game.d5.isKept){
            switch (game.d5.value) {
                case 1:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                    jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
                
            }
        }
        if(!game.d1.isKept){
            switch (game.d1.value) {
                case 1:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                    jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
            }    
        }
        if(!game.d2.isKept()){
            switch (game.d2.value) {
                case 1:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                    jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
            }
        }
        if(!game.d3.isKept()){
            switch (game.d3.value) {
                case 1:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                    jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
            }
        }
        if(!game.d4.isKept()){
            switch (game.d4.value) {
                case 1:
                    jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                     jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                     jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                     jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                     jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                     jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
            }
        }
        if(!game.d6.isKept()){
            switch (game.d6.value) {
                case 1:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice1.PNG")));
                    break;
                case 2:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice2.PNG")));
                    break;
                case 3:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice3.PNG")));
                    break;
                case 4:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice4.PNG")));
                    break;
                case 5:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice5.PNG")));
                    break;
                case 6:
                    jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/pkg1/Dice6.PNG")));
                    break;
                default:
                    break;
            }
        }  
    }
    
    public void next(){
        System.out.println("You have a current score of " + game.currentPlayer.playerScore + ". Click your button to refresh your score!");
        if(game.currentPlayer.getName() == game.p1.getName()){
            game.currentPlayer = game.p2;
        }else if(game.currentPlayer.getName() == game.p2.getName()){
            game.currentPlayer = game.p1;
        }
        System.out.println("It is now " + game.currentPlayer.getName() + "'s turn");
        resetBorder();
        resetDice();
    }
    
    public void testforWin(){
        
        if (game.currentPlayer.playerScore >= 10000){
            System.out.println("Looks like we have a winner");
            System.out.println(game.currentPlayer.getName() + " is the winner!");
            System.exit(0);
        }
    }
}

